name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  lychee:
    name: QA (Lychee)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: Run Lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --exclude ^https://github\.com/leptos-rs/leptos-lints.+#readme$ --cache --max-cache-age 1d . 

  cargo-machete:
    name: QA (Cargo Machete)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete
      - name: Run cargo-machete
        run: cargo machete --skip-target-dir

  unit-tests:
    name: Unit tests
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          matcher: false
      - name: Install Dylint
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-dylint,dylint-link
      - name: Run unit tests
        run: cargo test --all
